http:
  port : "8081"
  
  
db:
  host : "localhost"
  port : "3306"
  user : "root"
  database : "db"
  
sale:
  user : "Chetan@apisero.com"
  pass : "Ch@44626744"
  token : "QZuFpF0HbS4uWNq6c6bkovjuJ"